version: "1"



services:
  nats:
    image: nats
    ports:
      - 4222:4222
    networks:
      - edurtc

  redis:
    image: redis:6.0.9
    ports:
      - 6379:6379
    networks:
      - edurtc

  networks:
  ionnet:
    external: true
    name: edurtc
    driver: bridge